### ISSUE TITLE
Add basic scatterplot examples, one using base R and the other using ggplot2

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#10]
In the Scatterplot section add two basic scatterplot examples, one utilizing base R and one utilizing ggplot2. Note that even basic examples should have appopriate titles and axis labels.

**Comment by ChasGoldstein** [comment]
I claim this issue in the name of Mars. Isn't that lovely?

**Comment by mhhaney** [comment]
Chas has been assigned to work on this issue.
