### ISSUE TITLE
Add two basic bubble plot examples, one using base R and the other using ggplot2

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#11]
In the Bubble Chart section add two basic bubble chart examples, one utilizing base R and one utilizing ggplot2. Note that even basic examples should have appopriate titles and axis labels.

**Comment by peltodytes** [comment]
I would like to claim this.

- Ian

**Comment by mhhaney** [comment]
Yes. This one is assigned to Ian.

**Comment by mhhaney** [comment]
Nice work, @peltodytes!
