### ISSUE TITLE
Add diverging lollipop plot

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#13]
Add an example of a diverging lollipop plot, using base R, ggplot2, or both. Remember to add an appropriate title and axis labels.

**Comment by Leandron11** [comment]
Ill do this one !

**Comment by mhhaney** [comment]
OK. This one is now assigned to @Leandron11

**Comment by mhhaney** [comment]
@Leandron11 did a basic lollipop chart, so this issue is still open and up for grabs.

**Comment by mhhaney** [comment]
I'll take this one myself.
