### ISSUE TITLE
Add blank lines after code cells

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#24]
In RStudio's R Markdown it is best to leave a blank line after each code cell, particularly code cells that produce plots. To tackle this issue you should first pull upstream main to make sure your main code branch is up to date, then create a branch and check it out, then quickly add the blank lines where necessary, add, commit, push the branch to your origin, and make the pull request.

**Comment by awarhoftig** [comment]
I can handle creating blank lines as my first task

**Comment by kzodda** [comment]
hey @awarhoftig if you need any help lmk

**Comment by mhhaney** [comment]
This issue is assigned to @awarhoftig

**Comment by mhhaney** [comment]
I went ahead and took care of this one.
