### ISSUE TITLE
Add petal width histogram displayed as multiple histograms, one for each species

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#25]
At the end of the histograms section add an example (or examples, if you choose to do both base R and ggplot2) that breaks the petal width histogram into multiple histograms, one for each species of iris. If you use base R you can do this by creating multiple plots and using par to set the rows and columns parameters. In ggplot2 you can use facet_grid() or facet_wrap().

Make sure to put these examples at the end of the section to make it easier to merge in both these changes and the changes in issue #23

**Comment by paige-counihan** [comment]
I can work on this issue.

**Comment by mhhaney** [comment]
This issue is assigned to @paige-counihan.
