### ISSUE TITLE
Add example density plot added to a different plot at end of density plot section

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#26]
Add an example (either base R or ggplot2 or both) of a density plot added to another plot. For example, a density plot on top of a histogram or a density plot on top of a rug plot. Make sure to add it at the end of the section.

**Comment by emmyharvey3** [comment]
I can do this one

**Comment by mhhaney** [comment]
Assigned to @emmyharvey3
