### ISSUE TITLE
Density plot with groups

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#27]
Show one or more ways of breaking up a density plot by groups. You can do this with multiple plots on the same plot and the alpha parameter, ridgeline plots, or facets(ggplot2)/multiple plots in columns and rows (base R).

**Comment by MohamedSadek01** [comment]
I will do this one.

**Comment by mhhaney** [comment]
Assigned to @MohamedSadek01
