### ISSUE TITLE
Add basic bar chart examples using both base R and ggplot2.

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#3]
In the Bar Chart section add two basic bar chart examples, one utilizing base R and one utilizing ggplot2. Note that even basic examples should have appopriate titles and axis labels.

**Comment by emmyharvey3** [comment]
Can I do this one?

**Comment by mhhaney** [comment]
Yes. This one is now assigned to Emmy.
