### ISSUE TITLE
Add more strip chart examples (vertical and with categories)

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#35]
The current strip chart examples show distribution of one variable. Create two more strip charts (one base R and one ggplot2) that show the distribution of a numeric variable by a categorical variable. As an example, you could show the distribution of age by gender for the Titanic data.

**Comment by hfierle** [comment]
I will take this issue!

**Comment by mhhaney** [comment]
Hi @hfierle,

I already added a few, but you are welcome to add more if you would like. There may not be an easy way to do it in base R, so don't worry if your example is only implemented with ggplot2.
