### ISSUE TITLE
Add 2d Histogram Section with Examples

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#38]
Add a new section for 2d histograms, which are like scatterplots, but with color representing the data density in any particular area of the plot. 

With base R you can use the hexbin package. With ggplot2 you can use the geom_hex() or geom_bin2d().

**Comment by Shaglione** [comment]
I can volunteer to do this issue!

**Comment by mhhaney** [comment]
Assigned to @Shaglione
