### ISSUE TITLE
Add basic examples of stacked area plots, one using base R and another using ggplot2

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#4]
In the Stacked Area Plot section add two basic stacked area plot examples, one utilizing base R and one utilizing ggplot2. Note that even basic examples should have appopriate titles and axis labels.

**Comment by BrettReed98** [comment]
I would like to work on this issue.

**Comment by mhhaney** [comment]
OK. This one is assigned to @BrettReed98

**Comment by BrettReed98** [comment]
I have not found an example of a stacked area plot using base R. Should I just make two examples using ggplot2?

**Comment by mhhaney** [comment]
Yes, I don't see any examples for base R either, so just ggplot2 is fine for this one. Probably too complex to bother with in base R.
