### ISSUE TITLE
Add section for stacked bar plots

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#41]
Add section for stacked bar plots to the bar plots section. Build with both base R and ggplot2.

**Comment by Leandron11** [comment]
I'll try to complete this with the time we have left!

**Comment by mhhaney** [comment]
OK. This is assigned to @Leandron11

**Comment by mhhaney** [comment]
Oops. I accidentally closed this issue. Reopened now.
