### ISSUE TITLE
Add section for segmented stacked bar plots

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#42]
Add section for segmented stacked bar plots to the bar plots section. Build with base R and ggplot2.

(Also called a "relative frequency stacked bar plot" or a "percentage stacked bar plot," a segmented stacked bar plot is a stacked bar plot where the segments show the percentage of the whole)

**Comment by BrettReed98** [comment]
I'll do this one. Can use the steel data as an alternative to the area plot.

**Comment by mhhaney** [comment]
This is assigned to @BrettReed98
