### ISSUE TITLE
Add basic violin plot examples, one using base R and the other using ggplot2

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#6]
In the Violin Plot section add two basic violin plot examples, one utilizing base R and one utilizing ggplot2. Note that even basic examples should have appopriate titles and axis labels.

**Comment by kzodda** [comment]
Can I do this one? @mhhaney

**Comment by mhhaney** [comment]
Karl,
Sure, you can take this one. You have some good examples already. If you want to use the nba data please add a data folder to your repo and put the file in there. Then add it to the staging area when you are ready to commit your code changes.

**Comment by kzodda** [comment]
I submitted a pull request @mhhaney

**Comment by mhhaney** [comment]
Please submit another pull request, with the code added to the main .Rmd file. We are all working on the same file. The docs folder is only for the index.html file that is automatically generated when I knit the main .Rmd file.
