### ISSUE TITLE
Add basic examples of strip plot, using both base R and ggplot2

### ISSUE THREAD

**Issue by mhhaney** [mhhaney/r-base-graphics-and-ggplot2#7]
In the Strip Plot section add two basic strip plot examples, one utilizing base R and one utilizing ggplot2. Note that even basic examples should have appopriate titles and axis labels.

**Comment by emmyharvey3** [comment]
I can do this one

**Comment by mhhaney** [comment]
Great! This one is assigned to @emmyharvey3.
